modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "C0-1.0" # Review your options at https://choosealicense.com/.
[[mods]] #mandatory
modId = "natures_spirit" #mandatory
version = "1.0.0" #mandatory
displayName = "Nature's Spirit" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "multiloader.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
authors = "${mod_author}" #optional
description = '''
Nature Mod for the besties
''' #mandatory (Supports multiline text)
[[dependencies.natures_spirit]] #optional
modId = "terrablender" #mandatory
mandatory = true #mandatory
versionRange = "[3,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'